version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.2.0
    steps:
      - checkout
      - run: echo "hello world"
      - sonarcloud/scan

orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.3

workflows:
  main:
    jobs:
      - build:
          context: SonarCloud