version: 2.1

orbs:
  sonarcloud: sonarsource/sonarcloud@1.1.1

jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:2021.04
    steps:
      - sonarcloud/scan

workflows:
  example-workflow:
    jobs:
      - example-job